[package]
name = "cli-template"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
clap = { version = "3", features = ["cargo"]}
futures-util = "0.3.19"
solana-clap-v3-utils = "=1.11.1"
solana-cli-config = "=1.11.1"
solana-client = "=1.11.1"
solana-logger = "=1.11.1"
solana-remote-wallet = "=1.11.1"
solana-sdk = "=1.11.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
solana-validator = "=1.11.1"

[workspace]
